[package]
name = "system-alert"
version = "0.1.0"
edition = "2021"
authors = ["Marky"]
license = "MIT OR Apache-2.0"
description = "A Rust library for monitoring and visualizing system alerts."
homepage = "https://github.com/Marky-Shi/system_alert.git"
repository = "https://github.com/Marky-Shi/system_alert.git"
readme = "README.md"
keywords = ["system-monitor", "macos", "apple-silicon", "terminal-ui", "monitoring", "performance", "visualization"]
categories = [
    "command-line-utilities",
    "development-tools::profiling",
    "visualization",
]

[dependencies]
clap = "4.5.49"
termion = "4.0.3"
sysinfo = "0.37.2"
libc = "0.2.177"
tui = { version = "0.19", default-features = false, features = ['termion'] }
lazy_static = "1.4.0"
regex = "1.11.1"
tokio = { version = "1.43.0", features = ["full"] }
log = "0.4.20"
env_logger = "0.11.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"